### ISSUE TITLE
img2pdf.ImageOpenError after downloading

### ISSUE THREAD

**Issue by anaxonda** [MiniGlome/Archive.org-Downloader#1]
Hello,

Thanks a lot for this package. I tried downloading two books from archive.org. First worked successfully, for the second I get an error regarding img2pdf. All requirements seem to be met.

>[+] Successful login
[+] Successful loan
[+] Found 262 pages
Donwloading pages...
100%|█████████████████████████████████████████████████████████████████| 262/262 [02:59<00:00,  1.46it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/img2pdf.py", line 1349, in read_images
    imgdata = Image.open(im)
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f46f76bd450>

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/home/Downloads/archive_dl/Archive.org-Downloader/downloader.py", line 123, in <module>
    pdf = img2pdf.convert(images)
  File "/usr/lib/python3.9/site-packages/img2pdf.py", line 2032, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "/usr/lib/python3.9/site-packages/img2pdf.py", line 1353, in read_images
    raise ImageOpenError(
img2pdf.ImageOpenError: cannot read input image (not jpeg2000). PIL: error reading image: cannot identify image file <_io.BytesIO object at 0x7f46f76bd450>

Happy to share the archive.org book url, not sure if that violates github TOS.

**Comment by MiniGlome** [comment]
I think it might be because the downloaded images are not in .jpg format. I might be able to fix the problem if you give me the url of the book.

**Comment by MiniGlome** [comment]
Actually, the problem happens when downloading a pdf containing too many pages, the server starts responding differently after downloading 120~150 pages. I'll see if I can bypass this problem.

**Comment by MiniGlome** [comment]
Issue solved !

**Comment by anaxonda** [comment]
Works great now, thanks!
