### ISSUE TITLE
Allowing the script to handle non-ASCII special characters

### ISSUE THREAD

**Issue by grantbarrett** [MiniGlome/Archive.org-Downloader#10]
I download a lot of books in other languages which include a lot of non-ASCII special characters in their titles. The script as written strips out all but ASCII characters and numbers. However, if I remove the code that does the stripping, it seems to handle non-ASCII characters just fine. Change line 17 to `title = "".join([c for c in data['brOptions']['bookTitle']])`.

Here's an example book: [https://archive.org/details/dictionnairetymo0000bloc](https://archive.org/details/dictionnairetymo0000bloc)

It has é and ç in the title and they are preserved in the file name after the script change. 

Here are some other example books that have non-ASCII characters in their titles which worked with this script modification:

[https://archive.org/details/bdrc-W1AB6](https://archive.org/details/bdrc-W1AB6)
[https://archive.org/details/morisasakihindik0000unse](https://archive.org/details/morisasakihindik0000unse)
[https://archive.org/details/hindijapanesedic00kazu](https://archive.org/details/hindijapanesedic00kazu)
[https://archive.org/details/kainantohogenkis008800](https://archive.org/details/kainantohogenkis008800)

I'm guessing Python 2 users would really need the ASCII-only stripping, as it does not handle Unicode encodings automatically like Python 3 does. Yet the examples invoke python3, so that's what users should be using.

**Comment by MiniGlome** [comment]
fixed
