### ISSUE TITLE
IndexError When attempting to download a book

### ISSUE THREAD

**Issue by Stingerman06** [MiniGlome/Archive.org-Downloader#102]
I'm getting an index out of range error when attempting to download the Maximo : Ghosts to Glory Guide Book, to either PDF or JPG. Both options give an Index out of range error and the whole process just stops and aborts entirely.

> `1 Book(s) to download
[+] Successful login
========================================
Current book: https://archive.org/details/maximoghoststogl00hodg
[+] Successful loan
Traceback (most recent call last):
  File "C:\Users\curry\Archive.org-Downloader\archive-org-downloader.py", line 213, in <module>
    title, links, metadata = get_book_infos(session, url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\curry\Archive.org-Downloader\archive-org-downloader.py", line 20, in get_book_infos
    infos_url = "https:" + r.split('bookManifestUrl="')[1].split('"\n')[0]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

**Comment by maximka1812** [comment]
Some stuff changed in Archive.org response in past day or two.
Issue is not in downloader but in this.

**Comment by TheRabidWolverine** [comment]
The "bookManifestUrl" line is no longer working, the word is totally absent in the page content. Needs a change in code.

**Comment by TheRabidWolverine** [comment]
> Some stuff changed in Archive.org response in past day or two. Issue is not in downloader but in this. Seems like info still is present in "<input class="js-bookreader" type="hidden" part.
> 
> To be short - downloader processes HTML page and they just changed it.

Around 10.5 hours ago.

**Comment by maximka1812** [comment]
This part must be redone now, it seems like most data is present at <input class="js-ia-metadata" type="hidden" value='{

**Comment by MiniGlome** [comment]
Fixed with commit f68a668bed83bde73e1dd7b1001119d67f88484f
