### ISSUE TITLE
BookmanifestURL attribute not present in content, download failing

### ISSUE THREAD

**Issue by TheRabidWolverine** [MiniGlome/Archive.org-Downloader#103]
Around 10 hours ago, started seeing this error, where this particular line:

infos_url = "https:" + r.split('bookManifestUrl="')[1].split('"\n')[0]

started throwing exception. On debugging I found that the word "bookManifestUrl" is not present in the content fetched in the previous line any more:

r = session.get(url).text

Session login was successful as before, just this line is throwing error.
Please help.

SImilar issue I think - https://github.com/MiniGlome/Archive.org-Downloader/issues/102

**Comment by maximka1812** [comment]
Yep, all HTML changed, not one line.

Check <input class="js-ia-metadata" type="hidden" value='{ it seems like it is possible to rewrite stuff.

On my downloader version it needs more work, as I collect metadata to same into special PDF.

**Comment by TheRabidWolverine** [comment]
> Yep, all HTML changed, not one line.
> 
> Check <input class="js-ia-metadata" type="hidden" value='{ it seems like it is possible to rewrite stuff.
> 
> On my downloader version it needs more work, as I collect metadata to same into special PDF.

Yeah, looks like, it was deployed around 12 hours back. Please help. :)

**Comment by MiniGlome** [comment]
Fixed with commit f68a668bed83bde73e1dd7b1001119d67f88484f
