### ISSUE TITLE
Script doesnt work anymore

### ISSUE THREAD

**Issue by bunehh** [MiniGlome/Archive.org-Downloader#104]
python archive-org-downloader.py -e xxxx@gmail.com -p xxx -r 2 -u https://archive.org/details/introductiontoph0000anse
1 Book(s) to download
[+] Successful login
========================================
Current book: https://archive.org/details/introductiontoph0000anse
[+] Successful loan
Traceback (most recent call last):
  File "C:\Users\khogr\Archive.org\archive-org-downloader.py", line 213, in <module>
    title, links, metadata = get_book_infos(session, url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khogr\Archive.org\archive-org-downloader.py", line 20, in get_book_infos
    infos_url = "https:" + r.split('bookManifestUrl="')[1].split('"\n')[0]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by MiniGlome** [comment]
This was fixed in this commit f68a668bed83bde73e1dd7b1001119d67f88484f
You can pull the new version.
