### ISSUE TITLE
Error: index out of range

### ISSUE THREAD

**Issue by kallmand** [MiniGlome/Archive.org-Downloader#106]
After successful loan I get the following error:
```
[+] Successful loan
Traceback (most recent call last):
  File "C:\Users\KDani\Archive.org-Downloader\archive-org-downloader.py", line 213, in <module>
    title, links, metadata = get_book_infos(session, url)
  File "C:\Users\KDani\Archive.org-Downloader\archive-org-downloader.py", line 20, in get_book_infos
    infos_url = "https:" + r.split('bookManifestUrl="')[1].split('"\n')[0]
IndexError: list index out of range

```
I checked the URL twice, it seems to be OK. Last time I used the downloader, it worked fine, I didn't change anything since then. Any idea what might cause this and/or how to solve it? Many thanks!

**Comment by MiniGlome** [comment]
This issue has been fixed a few days ago, just get the last version and everything will be fine!

**Comment by kallmand** [comment]
> This issue has been fixed a few days ago, just get the last version and everything will be fine!

Great news, thank you very much! My bad, I didn't catch up with the latest changes.
