### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by 57E0** [MiniGlome/Archive.org-Downloader#111]
Hey, Lately when I want to use the script I get this message...  Is it possible to fix it somehow?

`[+] Successful loan
Traceback (most recent call last):
  File "/Applications/Archive/archive-org-downloader.py", line 213, in <module>
    title, links, metadata = get_book_infos(session, url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Archive/archive-org-downloader.py", line 20, in get_book_infos
    infos_url = "https:" + r.split('bookManifestUrl="')[1].split('"\n')[0]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

**Comment by MiniGlome** [comment]
This issue was fixed in the lastests commits. Just download the latest version to fix it.

**Comment by 57E0** [comment]
Ok, thank you for clarification. I haven't seen the closed issues tab ;)
