### ISSUE TITLE
Attempt to download returns HTTP 400 Bad Request

### ISSUE THREAD

**Issue by trettenbrein** [MiniGlome/Archive.org-Downloader#121]
I tried to download a book but got a HTTP 400 Bad Request:

```
patrick@Mac Archive.org-Downloader % python archive-org-downloader.py -e mail -p password -u url -r 0
1 Book(s) to download
[-] Error while login:
<Response [400]>
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.24.0</center>
</body>
</html>
```

I can confirm that the log-in details are correct (they work when I log-in on the actual web site). Could it be that archive.org changed the log-in procedure after the attach that happened some time ago? Is anyone else experiencing the same issue?

**Comment by TinyRaindrop** [comment]
Same issue for me.
I can't figure out how to modify the login function to make it work

**Comment by JeovinL** [comment]
same here

**Comment by AnthonyBronislavaGonzales** [comment]
None of you must have heard the news -- archive.org was under attack by weirdos and they have shut down all account login for now. Hopefully it comes back up. But yeah, this won't work for now.

**Comment by myfta** [comment]
Archive.org is back and you can log in, but this code does not work. It looks like something has changed probably to deter auto-logins.

**Comment by MiniGlome** [comment]
Thank you all for your feedbacks.
I fixed the script to reflect the new login method. You can pull the last commit and it will work as usual, with the same credentials.
