### ISSUE TITLE
some books not downling right

### ISSUE THREAD

**Issue by Impr0ve** [MiniGlome/Archive.org-Downloader#18]
I was having trouble downloading some books like on this link https://archive.org/details/brainsexrealdiff00moir/page/n263/mode/2up
it does the first 9 pages and then after that page goes temp unvailable :(
![temp unvail](https://user-images.githubusercontent.com/21207053/147841074-2b87a713-6941-4db2-86ec-0f099c38e75d.jpg)
page goes temp unvailable

**Comment by Bouboulov** [comment]
Just check the url and paste only the book url without "/page/etc."

**Comment by Impr0ve** [comment]
hey thank you! that worked :)
