### ISSUE TITLE
Option to not return book?

### ISSUE THREAD

**Issue by maf654321** [MiniGlome/Archive.org-Downloader#22]
Thanks for the tool, it works beautifully. Just wondering if it would be possible to add a flag that disables the auto-return of loaned books? I was trying to download both the pdf and jpgs of a particular book and had to reloan the book in order to make the two downloads, would be nice to be able to do multiple runs, in case something goes wrong, then choose to return the book. Thanks!

**Comment by i0Z3R0** [comment]
A temporary fix would be to remove line 214 which does return_loan() or remove lines 85-95 in the return_loan() function.
