### ISSUE TITLE
3 Feature Request - Bulk Download | Save as JPG | Return Book

### ISSUE THREAD

**Issue by L0garithmic** [MiniGlome/Archive.org-Downloader#3]
Feature Request 1: 
A way to bulk download multiple books. I have hard-coded the login details and book quality, all that's missing is some method to pass multiple URL's through the script. From maybe a text file?

Feature Request 2:
Output to individual JPG's in a folder or a compressed zip file, rather then a PDF. 

Feature Request 3:
Ability to return book after successful save of book images.

(Your script works AMAZING! These 3 features would make it... literally the best!)

**Comment by MiniGlome** [comment]
Great ideas! I'll make it soon.

**Comment by MiniGlome** [comment]
Done

**Comment by L0garithmic** [comment]
Dude, you are God among men! Working amazingly!

One fix I noticed needing done, your return code is not returning books. I was testing with these 2 books (bc they are so short lol) and it is not working. 
```
https://archive.org/details/flipflapbook0000unse
https://archive.org/details/flipflapspooky0000crow
```
I looked inside the py script and it seems the return url is hard coded
`	r = session.post("https://archive.org/details/horrorgamispooky0000bidd_m7r1", data=data)
`

Second off. Here is a script to throw into your readme. It allows people to download from a list in a txt file. All they need to do is make a txt file called downloader.txt. Put each book url on a new line then run the script in a .bat file. Works amazing.
`for /F "usebackq tokens=*" %%A in ("downloader.txt") do downloader.py -e craptotal@gmail.com -p 000000 -r 0 -u %%A --jpg`
or without jpg
`for /F "usebackq tokens=*" %%A in ("downloader.txt") do downloader.py -e craptotal@gmail.com -p 000000 -r 0 -u %%A`

**Comment by MiniGlome** [comment]
Of course I pasted the wrong url in the `return_loan` function, that's fixed.

You can now use the switch `-f` to import the urls from a file

**Comment by L0garithmic** [comment]
Dude... I can not believe how fast you are at this

Send me a cash-app ID or a bitcoin wallet ID. I will send you money. . I am dead serious and I insist... You have just saved me so many hours.

**Comment by MiniGlome** [comment]
Haha you're welcome! 😀

bc1qr9w4my5rgnxj80ul69sxhnrn9uc5982fg5lpjt

**Comment by L0garithmic** [comment]
Curious, What's the chance of multi-threaded? To deal with the fact that it downloads SLOOOWWW lol.
I currently run 4 different batch files with my file list split up 4 ways. Just curious how easily py can multi-thread.

No obligation, if it's a pain. Forget about it. Figured I would just ask.

**Comment by MiniGlome** [comment]
Another excellent idea!
I added multithreading and indeed the download is now extremely faster.

**Comment by L0garithmic** [comment]
Oh... My... Lord... You are amazing!!! Thank you so much!

**Comment by hawkeye2nd** [comment]
@MiniGlome - Seems Archive.org has now set some sort of throttling -  this happens after 5 or 6 books, then when I try again in a few minutes, after 1 or 2 books.  ```
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
