### ISSUE TITLE
Only downloads a few pages. 

### ISSUE THREAD

**Issue by Sephy1** [MiniGlome/Archive.org-Downloader#31]
I'm trying to download a rather large book but when it finishes only 10 or so pages are complete, the rest are a page that says "Page Temporarily unavailable. This page is part of a limited preview. Please try again tomorrow. Use your free account to borrow this book and gain access to all pages."

https://archive.org/details/shinmeikaikokugo0000unse/page/n9/mode/2up
here's the book if that helps.

Any help would be appreciated.

**Comment by MiniGlome** [comment]
Fixed with issue #35
