### ISSUE TITLE
This book does not need to be borrowed

### ISSUE THREAD

**Issue by nomentuum** [MiniGlome/Archive.org-Downloader#35]
It downloads the book but it does not borrow it and most pages are unavailable. If I manually borrow the book I can see all pages, but running the code does nothing but display repeatedly that the book does not need to be borrowed.

Trying to get https://archive.org/details/workbookforwheel00paul and https://archive.org/details/wheelockslatinre00whee.

It worked with other books without any problems!

Thanks for everything anyway!

<img width="812" alt="Screenshot 2022-06-25 002117" src="https://user-images.githubusercontent.com/108155682/175692958-eed0d0a5-470d-476e-9087-d5018954b1dd.png">
<img width="424" alt="Screenshot 2022-06-25 002320" src="https://user-images.githubusercontent.com/108155682/175692990-d5e3e0df-6f92-42fa-994b-7dbdd3198009.png">
<img width="1320" alt="Screenshot 2022-06-25 002410" src="https://user-images.githubusercontent.com/108155682/175693002-c36b5ee7-e334-47f9-939b-0aedace48bc3.png">
.

**Comment by nomentuum** [comment]
Trying to get https://archive.org/details/workbookforwheel00paul and https://archive.org/details/wheelockslatinre00whee. 

It worked with other books without any problems!

Thanks for everything anyway!

**Comment by MiniGlome** [comment]
The issue was that the url you used was https://archive.org/details/workbookforwheel00paul/mode/2up instead of https://archive.org/details/workbookforwheel00paul/
With this fix, you can now use both. I just improved the url parser that retrieves the book_id from the given url.

**Comment by nomentuum** [comment]
Thank you very much!
