### ISSUE TITLE
archive.org downloader, help

### ISSUE THREAD

**Issue by Montoro30** [MiniGlome/Archive.org-Downloader#37]
Hello, how are you?
Sorry to bother you, but I'd need a little help.

You published a very interesting code for downloading private files from "[archive.org](http://archive.org/)", but unfortunately I don't have much knowledge of python, I didn't understand where I should enter the data [email, password, desired link, quality and file type], everytime I run the program, it returns with the options and exits.

Could you please tell me where I should replace this information to perform the download?
Or maybe modify the code so that in the terminal it asks: "email, pass, desired link and quality"? In this way many people who don't know python can enjoy your great code.

By the way, I know that for you it seems very easy and it would be up to me to study python, however it wasn't for lack of will or commitment, but I don't have much aptitude for programming and I can't advance.

Thank you very much.

Best regards,
Montoro.

PS1: Do I need to borrow the book for your code to work?
PS2: img2pdf==0.4.0 doesn't install at all

**Comment by MiniGlome** [comment]
Hello,
I suggest you to google how to run a python script with arguments. It might be different if you run the script from a command line tool or an IDE like PyCharm.

- You don't need to borrow the book the script does it for you.
- How do you install this package? What is the error?

**Comment by Montoro30** [comment]
I have no idea how to do it... the basic course I took they always used PyCharm for everything... in fact that I learned is very different from that you used on this code.

mmm, about Linux terminal, unfortunately I use Windows 7.

img2pdf error:

PyCharm
File >> Settings >> add >> img2pdf v. 0.4.0 >> Install Package >> error: Microsoft Visual C++ 140 or greater is required.

but if it only has the function of converting to pdf, for me it is not important, it would be great to have the original jpg.

Thanks, I will research and try with the new information you kindly gave me.

**Comment by milahu** [comment]
> PyCharm

you dont need a python IDE just to run a python script ... just a terminal + python

> converting to pdf, for me it is not important

see #38 and add the `-j` flag

> about Linux terminal, unfortunately I use Windows 7

Archive.org-Downloader has the same CLI on all platforms

```sh
python archive-org-downloader.py -e alice@gmail.com -p xxxxxxxx -j -r 0 -u https://archive.org/yyyyyy
```

**Comment by Montoro30** [comment]
Great!
Forgive my stupidity and thank you for your patience.
You did a great job.
