### ISSUE TITLE
Download directories are nested instead of being deleted for each downloaded file

### ISSUE THREAD

**Issue by gumbolastima** [MiniGlome/Archive.org-Downloader#43]
I'm using the script on macOS 12.4 with Python 3.9.x (currently 3.9.13). I recently upgraded the script after being behind a few versions and the last two versions of the script have a bug where the directory that is created for each file isn't usually deleted. Instead, the next file's directory is created inside of that one, and the next one inside of that one, and so on. 

```
 - downloadFileDirOne
   - downloadFileDirTwo
     - downloadFileDirThree
```

It seems to be deleting only the directory of the last file downloaded from a download list and not each directory in turn as as they are emptied after PDFs are made. The expected behavior would be that the directory would be deleted after the PDF is made. 

I don't know enough about this, but my guess is that `directory` isn't being properly defined when looping for `shutil.rmtree(directory)` in line 225. Replacing this code at lines 209-216

```
		directory = os.path.join(directory, title)
		# Handle the case where multiple books with the same name are downloaded
		i = 1
		d = directory
		while os.path.isdir(directory):
			directory = f"{d}({i})"
			i += 1
		os.makedirs(directory)
```
with this code from an earlier version of the script solves the problem:

```
		directory = os.path.join(os.getcwd(), title)
		if not os.path.isdir(directory):
			os.makedirs(directory)
```

The "handle the case where multiple books with the same name are downloaded" doesn't seem  to be necessary at 209-216, at least according to my testing, because the case is already handled at lines 141-145 with:

```
	# Handle the case where multiple books with the same name are downloaded
	i = 1
	while os.path.isfile(os.path.join(directory, file)):
		file = f"{title}({i}).pdf"
		i += 1
```

Additionally, if the nest of folders is too deep, then an error occurs:

`Traceback (most recent call last):
  File "/Users/username/Archive.org-Downloader/archive-org-downloader.py", line 216, in <module>
    os.makedirs(directory)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 63] File name too long: "`

**Comment by MiniGlome** [comment]
Fixed
