### ISSUE TITLE
 pip install -r requirements.txt

### ISSUE THREAD

**Issue by HyperScorpio** [MiniGlome/Archive.org-Downloader#48]
Always give me a error in the MINGW32. 
bash: pip: command not found

I will be nice to see a video explain how to install this first and download one book. Thanks.

**Comment by MiniGlome** [comment]
This question is not related to the project, first learn how to use pip and run python scripts.

As the error states, pip is not installed. You should run ```py get-pip.py``` or ```python get-pip.py```.

**Comment by HyperScorpio** [comment]
Nothing works, i try to put the 2 folders names over the variable option and it doesn´t go right :(

**Comment by gary-w-achieve** [comment]
Chances

> Nothing works, i try to put the 2 folders names over the variable option and it doesn´t go right :( I'm using the latest python 310.

Chances are you have PIP installed.  Try running:
python3 -m pip install -r requirements.txt

That worked for me
