### ISSUE TITLE
Using —file for different URLs but with same name overwrites the previous PDFs

### ISSUE THREAD

**Issue by grantbarrett** [MiniGlome/Archive.org-Downloader#5]
When using the file list option and downloading four volumes from the same series — which have the same name in Internet Archive — they are given the same name by this downloader when the PDF is created, and therefore will overwrite each other. 

For example, the first four  results on this search are all different, even though they have the same title on their resepectice pages.

https://archive.org/search.php?query=Schweizer+lexikon&and[]=mediatype%3A%22texts%22

If you add all four URLs to your script, a the end you will end up with just the PDF of the final volume. 

For the moment, to drastically decrease the chances of this happening, I have used an available variable to add the page count to the file name when writing the PDF. This won't always prevent overwrites, however. 

The changed code:

`def make_pdf(pdf, title):
	with open(f"{title}-{len(links)}pp.pdf","wb") as f:
		f.write(pdf)
	print(f"[+] PDF saved as \"{title}-{len(links)} pp.pdf\"")
`

**Comment by MiniGlome** [comment]
fixed
