### ISSUE TITLE
Thank you so much! Your app is great!

### ISSUE THREAD

**Issue by quochung2310** [MiniGlome/Archive.org-Downloader#52]
As shown on the title, this is not an issue, but I don't know the how to say thank you except create one (I don't own any Bitcoins, unfortunately). 
You might not know how happy I am when I could not find a way to access a book on Archive.org which there is no pdf available, until I found your app.
Downloaded, installed, ran it and boom! The pdf file is in my desktop! Fantastic!

Again, thank you very much for your hard work!
Wish you all the best in your life!

**Comment by MiniGlome** [comment]
❤️

**Comment by MattAppleton** [comment]
Second this 'issue' — what a great tool!

Only slight snag I found is I needed to run `pip3 install requests` to get things moving...

thanks @MiniGlome !
