### ISSUE TITLE
Page numbering of .JPGs causing wrong order upon re-assembly

### ISSUE THREAD

**Issue by eggplantedd** [MiniGlome/Archive.org-Downloader#53]
I don't know the name / terms for this issue, but it's the same described here https://www.tenforums.com/general-support/165181-sort-problem-i-get-1-10-11-2-rather-than-1-2-how-do-i-fix.html

The 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 order will end up as 1, 11, 12 etc when re-assembled into a pdf with another program.

This isn't an issue with another program, just a classic filename issue. I thought I had solved this with Irfanview batch but I messed up enough times to come and ask for a fix 😛

**Comment by MiniGlome** [comment]
This is not an issue in the Windows Files Explorer, how do you want me to fix this ?

**Comment by darnn** [comment]
i think the idea would be to name the files 001, 002, 003 etc., unless it's a book with over a thousand pages, and then 0001 and so on.

**Comment by eggplantedd** [comment]
Yes- what darnn said would be advisable.

It's true it isn't an issue in Windows File Explorer at all- they are ordered correctly- but programs like img2pdf will not have the correct order.
