### ISSUE TITLE
"Invalid credentials" error 

### ISSUE THREAD

**Issue by cavefishin** [MiniGlome/Archive.org-Downloader#66]
Preface: I attempted to run this script on this setup:
- Windows 7 Ultimate x64 machine, fully updated up to current via ESU
- Python ver. 3.8.10; other necessary components like git were installed and ran correctly.

When trying to run the script to grab a currently borrowed book, I kept getting the same error referenced in (https://github.com/MiniGlome/Archive.org-Downloader/issues/36). Below are two examples of the variations that I typed in an attempt to fix the error:

- archive-org-downloader.py -e email@gmail.com -p 'P55sw0Rd' -u https://archive.org/details/metalheartismove0000lind -d C:\Users\Name\Desktop\folder -r 0
- archive-org-downloader.py -e 'email@gmail.com' -p 'P55sw0Rd' -u https://archive.org/details/metalheartismove0000lind -d C:\Users\Name\Desktop\folder -r 0

I still get an 'Invalid credentails!' error for both, so I am unsure what I'm doing wrong here.

**Comment by maximka1812** [comment]
Issue can be with C:\Users\Name\Desktop\folder

Can you show script output?

**Comment by cavefishin** [comment]
Sure. Example has a new URL, "archivebooks" folder on desktop, and CMD being run as administrator:
![output](https://user-images.githubusercontent.com/116922213/198839729-645a1b26-bca8-4f05-9961-f93d9ffd3bdb.png)

**Comment by maximka1812** [comment]
Remove ' from password and email, write them bare

**Comment by cavefishin** [comment]
Thank you for the assistance! I was able to successfully download the PDF in question after applying the above, and making sure the book was borrowed and opened in another tab while logged in before executing the command as follows.
![image](https://user-images.githubusercontent.com/116922213/199145156-314c82e1-7d9e-4ad1-b2a6-2a9e6615f634.png)

**Comment by maximka1812** [comment]
You can try my modified tool at https://github.com/maximka1812/AD---Archive-Download-Tool
