### ISSUE TITLE
Script does handle long names; suggested fix

### ISSUE THREAD

**Issue by grantbarrett** [MiniGlome/Archive.org-Downloader#8]
When trying to download files with long names, such as this one, https://archive.org/details/weiblauesschwarz0000fend, the file names are too long (on macOS 11.6, which has a 255 character file name limit).  Adding `title = title[:251]` at line 18 works to trim the title if it is longer than 251 characters, and allows enough room for the addition of ".pdf" later in the process.

**Comment by MiniGlome** [comment]
Thanks, it's fixed!

**Comment by grantbarrett** [comment]
'title = title[:245]' might be a better number to use to handle items with duplicate names *and* long names.
