### ISSUE TITLE
What does the "make sure you've already git installed" in the guide mean?

### ISSUE THREAD

**Issue by Linnshet** [MiniGlome/Archive.org-Downloader#84]
I'm completely new to Python, and a bit of a noob - have been looking for an answer the last hour. I obviously get syntax error, when I just put in my command.

**Comment by darnn** [comment]
I've done this a long time ago myself so I'm fuzzy on the details, but it just means you have to install Git itself, which I believe you can do by going here: https://gitforwindows.org/

**Comment by MiniGlome** [comment]
> I'm completely new to Python, and a bit of a noob - have been looking for an answer the last hour. I obviously get syntax error, when I just put in my command.

Git is used as a quick way to download the project. If you don't want to bother with Git, you can still download the project as a ZIP folder.
https://www.youtube.com/watch?v=CKcqniGu3tA
