### ISSUE TITLE
Download hangs

### ISSUE THREAD

**Issue by mrobe** [MiniGlome/Archive.org-Downloader#85]
Very often, the DL just hangs after a while.

Usually, I hit Ctrl-C a few times, and try again, but sometimes it takes several tries to get a PDF to DL.

Is there a problem such that the network connection drops but the downloader doesn't detect this?

Also, it would be nice if there were an option to only DL a folder full of lossless PNG files. Do-able?

Aside from these issues, this is a great app !!

**Comment by darnn** [comment]
I have a spotty connection and have had the same issues, but replacing my router fixed them, so I'm not sure it's the program's fault. As for lossless files, they're not stored on the server as PNGs but rather as JPGs, but yes, you can use these parameters to just download the files themselves: -r 0 -j
