### ISSUE TITLE
does this work on m1 macs?

### ISSUE THREAD

**Issue by mxradio** [MiniGlome/Archive.org-Downloader#86]
Program works fine on my intel mac. I get this error on silicon mac:

  src/core/annotation.cpp:4:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      src/core/nametree.cpp:4:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      src/core/numbertree.cpp:4:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      src/core/embeddedfiles.cpp:4:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      src/core/object.cpp:7:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      In file included from src/core/logger.cpp:4:
      src/core/pikepdf.h:10:10: fatal error: 'qpdf/QPDF.hh' file not found
      #include <qpdf/QPDF.hh>
               ^~~~~~~~~~~~~~
      src/core/object_convert.cpp:12:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      src/core/job.cpp:6:10: fatal error: 'qpdf/QPDFJob.hh' file not found
      #include <qpdf/QPDFJob.hh>
               ^~~~~~~~~~~~~~~~~
      src/core/object_repr.cpp:19:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      In file included from src/core/page.cpp:9:
      src/core/pikepdf.h:10:10: fatal error: 'qpdf/QPDF.hh' file not found
      #include <qpdf/QPDF.hh>
               ^~~~~~~~~~~~~~

 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pikepdf
Failed to build pikepdf
ERROR: Could not build wheels for pikepdf, which is required to install pyproject.toml-based projects

**Comment by sveinbjornpalsson** [comment]
Same.

**Comment by sveinbjornpalsson** [comment]
I went to the pikepdf repo, found these instructions:

> [gsvr](https://github.com/gsvr) commented [on Apr 3](https://github.com/pikepdf/pikepdf/issues/453#issuecomment-1493883105)
> I've encountered the same issue on Apple M1.
> This was resolved by first running `brew install qpdf` before installing via pip (`pip install pikepdf`)
> I suggest just adding a line to the docs that for Apple Silicon you might need to first install qpdf via brew install.

I tried it, seems to work.

**Comment by mxradio** [comment]
@sveinbjornpalsson 
Thanks very much, works for me too.

**Comment by MiniGlome** [comment]
This issue seems to be fixed
> I am going to close this now. Prior to pikepdf 8.0, I was building Apple Silicon manually on a laptop. It's now automated on Cirrus CI, so the build process should be much more stable.
_Originally posted by @jbarlow83 in https://github.com/pikepdf/pikepdf/issues/453#issuecomment-1636408425_
