### ISSUE TITLE
Very minor pasword turn bash error issue, but mainly a big ThankYou! great stuff

### ISSUE THREAD

**Issue by yoghurt-knitter** [MiniGlome/Archive.org-Downloader#92]
desktop:~/Archive.org-Downloader$ python3 archive-org-downloader.py -e email@proton.me -p 2E:q>!VZ;j!H%V_ -u https://archive.org/details/superinterestingbook/mode/2up -d ~/Downloads
bash: !VZ: event not found

dunno what bash: !VZ: event not found means, I am a newb, but I simply tried a different password and it worked great!

Thanks again!

**Comment by MrNanook** [comment]
Hi @yoghurt-knitter,

Put the password between quotes, like this: "2E:q>!VZ;j!H%V_ -u", or choose another password.

Your password contains the '!' character which apparently triggers the bash command ('!' allows you to search the bash history). Maybe @MiniGlome can look into this.

**Comment by NiciTheNici** [comment]
Try putting your password in quotes, "!" is a bash command. and needs to be escaped. You can read more about it here:
https://unix.stackexchange.com/questions/3747/understanding-the-exclamation-mark-in-bash
